-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Nov 16, 2022 at 03:55 AM
-- Server version: 5.7.36
-- PHP Version: 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shaadi_mubarak`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_login`
--

DROP TABLE IF EXISTS `admin_login`;
CREATE TABLE IF NOT EXISTS `admin_login` (
  `ID` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin_login`
--

INSERT INTO `admin_login` (`ID`, `username`, `password`) VALUES
(7, 'admin', 'ShaadiHoniChahiye@69420');

-- --------------------------------------------------------

--
-- Table structure for table `food`
--

DROP TABLE IF EXISTS `food`;
CREATE TABLE IF NOT EXISTS `food` (
  `food_id` int(2) NOT NULL AUTO_INCREMENT,
  `food_name` varchar(500) NOT NULL,
  `food_price` int(4) NOT NULL,
  `type` varchar(500) NOT NULL,
  PRIMARY KEY (`food_id`)
) ENGINE=MyISAM AUTO_INCREMENT=54 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `food`
--

INSERT INTO `food` (`food_id`, `food_name`, `food_price`, `type`) VALUES
(1, 'Kurkuri Amchoori Bhindi Chaat', 200, 'Appetizer'),
(2, 'Beetroot and Feta Tikki', 180, 'Appetizers'),
(3, 'Stuffed Tandoori Platter', 170, 'Appetizers'),
(4, 'Assorted Vegetable Pakoras', 165, 'Appetizers'),
(5, 'Paneer Chandini Seekh', 170, 'Appetizers'),
(6, 'Amravati Kozhi Varuval', 195, 'Appetizers'),
(7, 'Tawa Shrimp Roast', 180, 'Appetizers'),
(8, 'Amritsari Fish Fry', 180, 'Appetizers'),
(9, 'Mughlai Paneer Tikka', 175, 'Tandoori and Grills'),
(10, 'Peshwari Bharwan Aloo', 170, 'Tandoori and Grills'),
(11, 'Tandoori Subzi Platter', 180, 'Tandoori and Grills'),
(12, 'Tandoori Chicken', 210, 'Tandoori and Grills'),
(13, 'Chicken Chops Afghani', 165, 'Tandoori and Grills'),
(14, 'Murg Makhan Malai', 160, 'Tandoori and Grills'),
(15, 'Classic Chicken Tikka', 170, 'Tandoori and Grills'),
(16, 'Murgh Reshmi Kabab', 180, 'Tandoori and Grills'),
(17, 'Tandoori Shrimp', 200, 'Tandoori and Grills'),
(18, 'Moghul Signature Malai Kofta', 210, 'Main Course'),
(19, 'Chukunder Sham Savera', 200, 'Main Course'),
(20, 'Paneer Jalfrezi', 220, 'Main Course'),
(21, 'Old Delhi Butter Paneer', 180, 'Main Course'),
(22, 'Paneer Mirch Ka Salan', 190, 'Main Course'),
(23, 'Methi Malai Mattar', 190, 'Main Course'),
(24, 'Channa Amritsari', 185, 'Main Course'),
(25, 'Subzi Diwani Handi', 180, 'Main Course'),
(26, 'Classic Bhindi Masala', 175, 'Main Course'),
(27, 'Old Delhi Butter Chicken', 200, 'Main Course'),
(28, 'Murg Tikka Masala', 210, 'Main Course'),
(29, 'Badshai Murgh ka Salan', 200, 'Main Course'),
(30, 'Murgh Hyderabadi Curry', 220, 'Main Course'),
(31, 'Naan/Butter Naan/Roti', 25, 'Rotis'),
(32, 'Aloo Paratha/Pudina Paratha/ Kabuli Paratha', 30, 'Rotis'),
(33, 'Kandhari Naan', 25, 'Rotis'),
(34, 'Chilli Cheese Naan/Kheema Naan', 30, 'Rotis'),
(35, 'Bullet Naan', 35, 'Rotis'),
(36, 'Chapati', 20, 'Rotis'),
(37, 'Plain Basmati', 140, 'Rice'),
(38, 'Kashmiri Pulao', 170, 'Rice'),
(39, 'Veg Biryani', 180, 'Rice'),
(40, 'Lachnawi Veg Dum Biryani', 185, 'Rice'),
(41, 'Lachnawi Murgh Dum Biryani', 200, 'Rice'),
(42, 'Shrimp Biryani', 240, 'Rice'),
(43, 'Goat Dum Biryani', 280, 'Rice'),
(44, 'Raita', 120, 'Accompaniments'),
(45, 'Dahi Bhalla', 130, 'Accompaniments'),
(46, 'Green Salad', 125, 'Accompaniments'),
(47, 'Masala Papad', 80, 'Accompaniments'),
(48, 'Kulfi Falooda', 90, 'Desserts'),
(49, 'Gulab Jamun', 90, 'Desserts'),
(50, 'Ice Creams', 100, 'Desserts'),
(51, 'Gajjar Halwa', 110, 'Desserts'),
(52, 'Lava Cake', 140, 'Desserts'),
(53, 'Casata Ice Cream', 140, 'Desserts');

-- --------------------------------------------------------

--
-- Table structure for table `guest`
--

DROP TABLE IF EXISTS `guest`;
CREATE TABLE IF NOT EXISTS `guest` (
  `user_id` int(10) NOT NULL,
  `food_guest` int(10) NOT NULL,
  `tran_guest` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `master_list`
--

DROP TABLE IF EXISTS `master_list`;
CREATE TABLE IF NOT EXISTS `master_list` (
  `item_id` int(10) NOT NULL AUTO_INCREMENT,
  `item_category` varchar(500) NOT NULL,
  `item_name` varchar(500) NOT NULL,
  `item_description` mediumtext,
  `price` int(10) NOT NULL DEFAULT '1',
  `location` varchar(500) DEFAULT NULL,
  `state` varchar(500) DEFAULT NULL,
  `city` varchar(500) DEFAULT NULL,
  `food_category` varchar(500) DEFAULT NULL,
  `food_type` varchar(500) DEFAULT NULL,
  `images` varchar(500) DEFAULT NULL,
  `status` varchar(500) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`item_id`) USING BTREE,
  UNIQUE KEY `item_name` (`item_name`)
) ENGINE=MyISAM AUTO_INCREMENT=202 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `master_list`
--

INSERT INTO `master_list` (`item_id`, `item_category`, `item_name`, `item_description`, `price`, `location`, `state`, `city`, `food_category`, `food_type`, `images`, `status`) VALUES
(17, 'food', 'Tandoori Chicken', 'Tender Chicken Marinated With Tandoori Spices.', 210, '', '', '', 'tandoori and grills', 'non veg', 'img.jpg', 'active'),
(16, 'food', 'Mughlai Paneer Tikka', 'Shrimps Are Cooked In Traditional Iron Skillet With A Spicy Lemony Marinade.', 175, '', '', '', 'tandoori and grills', 'veg', 'img.jpg', 'active'),
(14, 'food', 'Kurkuri Amchoori Bhindi Chaat', 'An All-Time Favorite Spiced Okra Fry Finished With Dry Mango Powder And Turned Into A Signature Chaat', 200, '', '', '', 'appetizers', 'veg', 'img.jpg', 'active'),
(15, 'food', 'Tawa Shrimp Roast', 'Shrimps Are Cooked In Traditional Iron Skillet With A Spicy Lemony Marinade.', 180, '', '', '', 'appetizers', 'non veg', 'img.jpg', 'active'),
(13, 'venues', 'ITC Rajputana', 'ITC Rajputana, an exotic and stylish red-brick heritage hotel in the capital city of Rajasthan, is symbolic of regal hospitality that harks back to a glorious past. The opulent hotel has many versatile venues, and the space can be further expanded for a large gathering by using a courtyard with the separate entrance. Siddhartha Chaturvedi, of Weddings by Event Crafter, shares, â€œITC Rajputana has a classic and authentic appeal which attracts a lot of millennial couples wanting to host a destination wedding in Jaipur. It has adequate rooms to accommodate large wedding groups.â€', 500, 'Dev Nagar, Jodhpur', 'rajasthan', 'Jodhpur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(1, 'venues', 'Umaid Bhawan Palace', 'Home of Jodhpurâ€™s erstwhile royal family and currently the worldâ€™s sixth-largest private residence, the Umaid Bhawan Palace affords views of the historical Blue City, vast dunes, as well as the nearby Mehrangarh Fort. Known for its rich heritage, yellow sandstone architecture, and luxurious amenities, this property managed by the Taj Group, has become a hot spot for celebrity weddings such as that of Priyanka Chopra Jonas and Nick Jonas. Wedding designer Ashish Bohra, of Perfexion Events, shares, â€œStrolling through the lush, landscaped Baradari Lawns with dancing peacocks at Umaid Bhawan is a magical experience, and the property is perfect for those who have always envisioned a fairy tale wedding.â€', 500, 'Cantt Area, Jodhpur', 'rajasthan', 'Jodhpur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(18, 'food', 'Moghul Signature Malai Kofta', 'Potato And Cheese Croquettes In A Mild Nutty Sauce', 210, '', '', '', 'main course', 'veg', 'img.jpg', 'active'),
(19, 'food', 'Old Delhi Butter Chicken', 'A Classic Old Delhi Style Signature Recipe Of World-Famous Butter Chicken', 200, '', '', '', 'main course', 'non veg', 'img.jpg', 'active'),
(20, 'food', 'Naan/Butter Naan/Roti', '', 25, '', '', '', 'rotis', 'veg', 'img.jpg', 'active'),
(21, 'food', 'Aloo Paratha/Pudina Paratha/Kabuli Paratha', '', 30, '', '', '', 'rotis', 'veg', 'img.jpg', 'active'),
(22, 'food', 'Plain Basmati', 'A Variety Of Long, Slender-Grained Aromatic Rice', 140, '', '', '', 'rice', 'veg', 'img.jpg', 'active'),
(23, 'food', 'Lucknawi Murgh Dum Biryani', 'Lucknowi Biryani Is Cooked With The Dum Method In A Handi ,Where The Rice And Vegetables Are Cooked Separately And Then Layered In Alternate Layers With Marinated Chicken, Flavoured With Rose And Kera Essence (Ittars) And Cooked On Slow Flame With The Top Sealed Tightly.', 200, '', '', '', 'rice', 'non veg', 'img.jpg', 'active'),
(24, 'food', 'Raita', 'Yoghurt Mix-Cucumber,Onion,Fresh Mint,Chopped Pineapple And Bhoondhi', 120, '', '', '', 'accompaniments', 'veg', 'img.jpg', 'active'),
(25, 'food', 'Masala Papad', 'Fried Lentil Crispies,Topped With Choppen Onion,Tomato,Green Chili And Cilantro', 80, '', '', '', 'accompaniments', 'veg', 'img.jpg', 'active'),
(26, 'food', 'Kulfi Falooda', 'Traditional Indian Ice Cream Flavored With Saffron And Pistachio Served With Falooda And Rabri', 90, '', '', '', 'desserts', 'veg', 'img.jpg', 'active'),
(27, 'food', 'Gulab Jamun', 'Deep Fried Roundels Of Cottage Cheese And Flour Soaked In Saffron Flavored Sugar Syrup', 90, '', '', '', 'desserts', 'veg', 'img.jpg', 'active'),
(50, 'photography', 'Vijayeesam Photography', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(48, 'photography', 'Technovision', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(49, 'photography', 'Varun Gavli Studio', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(46, 'photography', 'Photo by the Wedding Ties', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(47, 'photography', 'Suraj Studio', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(45, 'photography', 'Parak Studio', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(44, 'photography', 'Light Chamber', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(43, 'photography', 'Daas Photography', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(42, 'photography', 'Banga Studio', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(41, 'photography', '90sBlack', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(52, 'sound and lights', 'Absolut Lime', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(53, 'sound and lights', 'D&S Djs', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(54, 'sound and lights', 'Dj Ganesh', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(55, 'sound and lights', 'Dj Santosh', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(56, 'sound and lights', 'Dj Vibes', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(57, 'sound and lights', 'Dj Wale Babu', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(58, 'sound and lights', 'Elite Dj Planners', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(59, 'sound and lights', 'Miami Djs', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(60, 'sound and lights', 'Royal Djs', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(61, 'sound and lights', 'RP Dj Wale', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(67, 'food', ' SWEET POTATO TIKKI', 'Boiled, mashed sweet potatoes are spiced with few Indian spices and shaped into tikki (patty) and shallow fried in the pan. ', 170, '', '', '', 'appetizers', 'veg', 'j3.jpg', 'active'),
(76, 'food', 'PALAK CHAAT', 'Crispy spinach leaves are coated with gram flour batter and deep fried in the oil. Then topped with chutneys (green chutney and meethi chutney), yogurt, sev, chaat masala and coriander leaves.', 180, '', '', '', 'appetizers', 'veg', 'j4,jpg', 'active'),
(69, 'food', 'VEG LOLLYPOP', 'Stuffing of veggies and mixed well with mashed potatoes, with spicy soya sauce dip.', 170, '', '', '', 'appetizers', 'veg', 'j2.jpg', 'active'),
(70, 'food', 'BANG BANG CAULIFLOWER', 'Here panko breadcrumbs coated cauliflower florets are air-fried until crisp and tossed into sweet, spicy and creamy bang bang sauce. ', 175, '', '', '', 'appetizers', 'veg', 'j5.jpg', 'active'),
(71, 'food', 'Saag Paneer', 'The perfect dish to liven up any meal, this traditional spinach and paneer recipe is simply delicious with the warming flavours of our Madras Spice Paste.', 210, '', '', '', 'main course', 'veg', 'j6.jpg', 'active'),
(72, 'food', 'Tandoori Chicken Wings', 'Whether youâ€™re in the mood for a summer BBQ or a cozy baked meal, this recipe can be made in the oven or on the grill. Whichever method you choose will bring out the flavours of ginger, tamarind and tandoori spices in our Indian paste.', 195, '', '', '', 'tandoori and grills', 'non veg', 'j7.jpg', 'active'),
(73, 'food', 'Tandoori Chicken Salad', 'Chicken cooked in aromatic Indian spices served along with strawberries on a bed of salad.', 200, '', '', '', 'accompaniments', 'non veg', 'j8.jpg', 'active'),
(74, 'food', 'VEGETABLE KORMA', 'Korma is a perfect alternative to a mild Mango Chicken or a Pasanda Cooking Sauceâ€”sweet and flavoursome, with the flavours of Indian spice still really coming throughâ€”this is set to become a family favourite.', 200, '', '', '', 'main course', 'veg', 'j9.jpg', 'active'),
(75, 'food', 'Tandoori Roasted Eggplant', 'njoy the mix of deliciously warm eggplants, with fresh mint and Greek yogurt, with a snap of pomegranate to finish.', 210, '', '', '', 'tandoori and grills', 'veg', 'j10.jpg', 'active'),
(77, 'food', 'WARM LENTIL SALAD', '', 200, '', '', '', 'accompaniments', 'veg', 'j11.jpg', 'active'),
(78, 'food', 'LAMB KEBABS', 'Our lovely versatile Mild Curry Spice Paste brings the flavours of wonderful Indian spices to juicy, tender lamb- in a way that is tantalizingly tasty.', 240, '', '', '', 'tandoori and grills', 'non veg', 'j12.jpg', 'active'),
(79, 'food', 'MANGO CHUTNEY TOPPED SORBET', '', 210, '', '', '', 'desserts', 'veg', 'j13.jpg', 'active'),
(80, 'food', 'SAFFORAN SHEMIYA KHEER', '', 210, '', '', '', 'desserts', 'veg', 'j14.jpg', 'active'),
(81, 'food', 'MANGO SHRIKHAND', 'mildly sweetened yogurt is studded with mango pieces and served with a zesty mango salad.', 220, '', '', '', 'desserts', 'veg', 'j15.jpg', 'active'),
(82, 'food', 'SHAHI TUKDA', 'Marut Sikka whips up a rich, saffron infused shahi tudka from Awadh. ', 210, '', '', '', 'desserts', 'veg', 'j16.jpg', ''),
(83, 'food', 'KULFI', 'A popular frozen dessert that is sinfully rich, dense and creamy. Reduced milk flavoured with saffron, cardamom, pistachio and almonds, served chilled. ', 80, '', '', '', 'desserts', 'veg', 'j17.jpg', 'active'),
(85, 'venues', 'GCC Hotel and Club', 'Since 1933, GCC Hotel and Club is amidst the 3-star hotels in the city of Mumbai which provides               best-in-class services to its clients.               GCC Hotel and Club is a spectacular place for all kinds of events. Whether it is a big fat Indian wedding               or a small cocktail party, its modern facilities and the sophisticated interiors will definitely impress               you. GCC Hotel and Club offers more than 90,000 sq. ft. lawn space to take your wedding party to the next               level. Its three spacious banquet halls can accommodate 50 to 500 people any time. With more than one               event space, they also provide you with guest accommodation and basic facilities like valet parking.', 87000, 'Mira Road,Mumbai', 'maharashtra', 'Mumbai', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(86, 'venues', 'Eskay Resorts', 'Since 1933, GCC Hotel and Club is amidst the 3-star hotels in the city of Mumbai which provides               best-in-class services to its clients.               GCC Hotel and Club is a spectacular place for all kinds of events. Whether it is a big fat Indian wedding               or a small cocktail party, its modern facilities and the sophisticated interiors will definitely impress               you. GCC Hotel and Club offers more than 90,000 sq. ft. lawn space to take your wedding party to the next               level. Its three spacious banquet halls can accommodate 50 to 500 people any time. With more than one               event space, they also provide you with guest accommodation and basic facilities like valet parking.', 110000, 'Borivali - Kandivali, Mumbai', 'maharashtra', 'Mumbai', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(87, 'mehendi', 'Mansi Bridal Mehndi Artist', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(88, 'mehendi', 'Heena Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(89, 'mehendi', 'Arabic Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(90, 'mehendi', 'Classic Heena', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(91, 'mehendi', 'Sneha Traditional Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(92, 'mehendi', 'Payals Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(93, 'mehendi', 'Nisha Bridal Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(94, 'mehendi', 'Ayush Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(95, 'mehendi', 'Sayali Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(96, 'mehendi', 'Bridal Mehndi', '', 500, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(97, 'venues', 'Novotel', 'They come up with a number of facilities and amenities to call your marriage ceremony the most luxurious               time of your life. With everything under one roof, it becomes really easy for you to book this venue for               your wedding night. Welcome to this paradise with open arms and celebrate each day and function in their               beautiful and full of splendid architecture in their wedding halls. With their in-house salon services,               half               of your burden of a makeup artist gets lowered down! A perfect venue with the best quality and everything               worth the price youve paid for your wedding.', 91000, 'Balraj Sahni Marg, RB Beach, Konkan', 'maharashtra', 'konkan', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(98, 'venues', 'The Tamarind Tree', 'The Tamarind Tree , is a place where the old, the new, and someplace magical are crafted into an exquisite               tapestry. Nestled in a five-acre garden of beautiful trees including the original tamarind tree after               which it was named, a natural pond, colonial Bandstand, elegant pavilions, and ample open spaces, The               Tamarind Tree is a place like none other. It is the perfect place for a celebration, your wedding. A               wedding is one of the best days of your life and you surely want to have a great time, since you are about               to start a new life ahead with your better half. You wish to look out for the best venue where you can               accommodate your guests, serve with awesome, lip-smacking food and yes, you surely look forward to a               location with a number of facilities.', 94000, '88, Kanakapura Road, Nashik', 'maharashtra', 'Nashik', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(99, 'venues', 'The Groves', 'The Groves is a stunning venue and can be a wonderful location for the biggest day of your life. It               presents an opportunity for a couple to hold a wedding at a romantic location without spending a fortune,               surrounded by lush green mango trees and thick vegetation. The venue harmoniously combines nature with               modernity, Swaggering voguish plushy rooms, each coming with its own balcony facing the pool and crisp air               from the verdure of trees. Delightful cocktail parties with the sunken bar in the pool for the guests, an               enclosed area connecting three main spaces together.', 99000, 'The Groves, Kada Agrahara Main Road, Rampura, Amravati', 'maharashtra', 'Amravati', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(100, 'venues', 'Arena100 Sports and Recreation', ' Arena100 Sports and Recreation is one of the most               sought-after banqueting facilities in the city. It was set up with a view to providing an elegant and               superior banqueting space to cater to the varied requirements of their clients. Whatever the celebration               may be, big or small, it is their endeavor to make each celebration, a grand success. They are perfect               when it comes to hosting wedding ceremonies as they offer heavenly views combined with lavish hospitality.               Their warm welcoming nature and hospitality make your wedding experience very special. The location adds               another level of desire to this venue as it is situated on the outskirts, away from the noise and bustle               of the city. The venue has outdoor spaces that can accommodate up to 800 people. They have a flexible               catering policy. They also provide ample parking space for the guests.', 100000, 'Arena100 Sports and Recreation City ,Bypass Road, Aurangabad', 'maharashtra', 'Aurangabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(102, 'venues', 'Conrad Pune', 'Conrad Pune is the Hilton companys first luxury hotel in               India. An iconic structure in the heart of Punes dynamic central business district, the striking Conrad               Pune is only minutes from major corporations, key government institutions and premier residential               neighborhoods. It is a place to stay inspired. They offer their guests one-of-a-kind experiences with               sophisticated, locally inspire the surroundings. Service offered is more than personal, its intuitive.               While your stay at hotel, your connections to people and places around the corner, and half way around the               world will be at best. The hotel takes the responsibility of meeting every couple need. The wedding at               this place will help you to pile memories bit by bit in an organised manner.', 89000, 'Conrad, 7, Mangaldas Road, Sangamvadi, Pune', 'maharashtra', 'Pune', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(103, 'venues', 'Dhepe Wada', 'Dhepe Wada is a banquet hall located in the city of Pune.               Choosing a venue for your wedding and all its other related events is not an easy decision to make. You               have to search for multiple options, visit them, compare everything. To ensure that all your wedding               functions area a successful one, Dhepe Wada offers all the facilities and services which you might require               to host your perfect wedding and forge happy and everlasting reminiscences with your loved ones. You will               get a whole set of services and facilities to make your function as a smooth one.', 120000, 'Erandwane, Pune', 'maharashtra', 'Pune', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(104, 'venues', 'Prathamesh Resorts', 'Nestled in the Sahyadri ranges Prathamesh Resorts is the               ideal destination for your fairytale wedding. Experience the magic of nature and wedding rituals with               breathtaking locale. We provide customized packages to make your wedding look like one dreamy affair. Your               Perfect wedding destination is just a click away!', 88500, 'Prathamesh Resorts, Khed Shivapur', 'maharashtra', 'Khed Shivapur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(105, 'venues', 'TouchWood Resort', 'Located in the mystic hills of Igatpuri, surrounded by               green mountains; enriched with fog & waterfalls, Touchwood Bliss is a nature-inspired banquet hall and               wellness destination located in Igatpuri. With 6 Fully Equipped AC Glamping Tents and, 4 Courtyard               Villas,4 Farmside Villas, this venue hopes to bring you closer to nature while providing a comfortable               stay and a pure veg restaurant serving some delicious food, including Jain preparations. It is a venue               with a serene ambience and spacious interiors that one would need for events of all sizes. This venue is               perfect for grandly hosting your pre-wedding, wedding, and post-wedding functions.', 100000, 'Igatpuri, Nashik', 'maharashtra', 'Nashik', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(106, 'venues', 'Bay 15 Waterfront', 'Just 6 kms from the capital city of Panjim, the Bay 15 Waterfront is located at the famous Odxel beach               which provides for breathtaking views of the Arabian Sea. It is a stand-alone venue which is one of Goas               largest waterfront wedding lawns offering its own in-house catering services at a 5-star level. It is a               beautiful, hospitable place for tourists and for people, who are looking lovely venue for their wedding               ceremony.', 80000, 'Odxel Beach, Dona Paula, Panaji, Goa', 'goa', 'Panaji', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(107, 'venues', 'Silva Heritage', 'Silva Heritage in Goa is one of the most sought-after banqueting facilities in the city. It was set up               with a view to providing an elegant and superior banqueting space to cater to the varied requirements of               their clients. Whatever the celebration may be, big or small, it is their endeavor to make each               celebration, a grand success. They are perfect when it comes to hosting wedding ceremonies as they offer               heavenly views combined with lavish hospitality. Their warm welcoming nature and hospitality make your               wedding experience very special. The location adds another level of desire to this venue as it is situated               on the outskirts, away from the noise and bustle of the city. The venue has outdoor spaces that can               accommodate up to 400 people. They have a flexible catering policy. They also provide ample parking space               for the guests.', 92000, 'Silva Heritage, Cana, Benaulim, Goa, India', 'goa', 'Benaulim', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(108, 'venues', 'Prainha Beach Resort', ' A Prainha wedding at any time of day is beautiful, but a Prainha sunset wedding is particularly               spectacular. Prainha Goa is a stunning location for a wedding as paradise awaits at Prainha Resort by the               Sea. A serene resort, nestled on a secluded cove in Dona Paula. Indulge in the tranquil sensation of this               quiet retreat, where natures supreme beauty creates a mesmerizing backdrop for your sublime relaxation.', 100000, ' Shetty Road, Cana, Benaulim, Goa, Indi', 'goa', 'Benaulim', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(109, 'venues', 'DoubleTree by Hilton, Panaji', ' Enjoy 5-star service at the DoubleTree by Hilton, Panaji. Set on the Old Goa Road, just minutes from               jewels of India like the Anjuna Beach, their luxury hotel offers easy access to all points of interest.               Take a dip in their pool or break a sweat in the state-of-the-art fitness center. Their City of Love              location is ideal for vacations, weddings, getaways and even for business. Convenient to Goa Airport, this               5-star hotel welcomes you with traditional Indian hospitality in a modern setting. Fully equipped with               work class facilities, they offer 160 luxurious room & suites for comfortable accommodation and stay for               everyone. For the celebration area, they offer customized spaces that include one indoor hall, one outdoor               lawn space, and a poolside space..', 85000, 'Kadamba Plateau Panjim, Old Goa Rd, Goa Velha, Goa', 'goa', 'Panaji', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(110, 'venues', 'Radisson Blue Resort Goa, Cavelossim Beach', ' Radisson Blu Resort Goa is located just 45 minutes from Dabolim International Airport and is near popular               beaches like Colva, Palolem and Calangute. The whole hotel is designed keeping in mind Goan-Portugese               architecture. Guests appreciate the in-house spa and large swimming pool which the hotel has to offer.               There are 132 rooms and suites which portray mesemrizing views of the pool or lawn, and all accommodations               are contained with chic furnishings and modern amenities. They also offer 4,000 square meters of event               space for weddings and corporate events. They also have grand lawns which accommodate upto 750 attendees               for outdoor weddings.', 98000, 'Cavelossim, Beach, Mobor Beach, Goa', 'goa', 'Panaji', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(111, 'venues', 'Taj Fort Aguada Resort & Spa, Goa', 'Taj Fort Aguada Resort & Spa, Goa is at its best. Romantic. Charming. Vibrant. It has history woven in its               walls. Its where royalty, heads of government and the biggest celebrities are known to frequent. For the               luxury Goa experience, which no other place has been able to recreate. Not much has changed. The               picturesque settings creates a fantastic backdrop to the entire experience, added to which the nouvelle               restaurants and the Jiva spa will make you go Ah! Soak in the space that showcases the spirit of Goa. The               45 km drive from the airport will have you delighting in backseat surprises (were not revealing here).               Explore the horizon as you look over the infinity pool, beyond the 16th century ramparts of the Portuguese               Fort, and wave back to the tide as it works its way across the Arabian Sea to joyfully greet the Sinquerim               beach below.', 120000, 'Beach Sinquerim, Candolim, Goa', 'goa', 'Candolim', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(112, 'venues', 'The Fort Ramgarh', '          Marriages are made in the heaven which we formalize on the Earth! A Royal wedding is an ideal way to               respect the beginning of your married life. A Royal Wedding experience is one of its kind, a Dreamland of               Kings & Queens, Maharajas & Maharanis with elegantly decorated well lit Palace, a Patiala backdrop               giving the real Royal touch feeling to you and your guest for A Grand Celebration! - Tikka ceremony,               Garlands will receive your esteemed guests through the Tallest Wooden Gate in the country (Recorded in               Limca Book of Records). The only destination to turn your dream wedding into reality & memorable day of               your life with a touch of perfection and Royal Hospitality. A Fairytale Royal Wedding experience with the               processions of caparisoned Elephants & Entertainment by Folk dancers, Musicians, Shehnai Vadan, Fire               Performers, Dhol Wales and much more..', 130000, 'The Fort Ramgarh, National Highway', 'goa', 'Candolim', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(113, 'venues', 'Redwood Resorts', '             Redwood Resort, situated amidst the serene backdrop of Morni town. A haven of tranquility where the only               sounds being the wind softly rustling among the trees and the distant calls of birds. Wide stretches of               greens meet the eye at length with sights as soothing as the dancing and joyous peacocks. Redwood offers               comfort and luxury in natures lap, with 23 well equipped rooms perfectly suited for your needs, then               Redwood Resorts can be the perfect location. Redwood resorts has illustrious impeccable dÃ©cors, elite               services, unrivaled array of amenities and striking venues, at economical prices..', 99000, 'Morni Road', 'goa', 'Candolim', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(114, 'venues', 'Kanha Banquet Hall', '.Kanha Banquet Hall is one of the most sought-after banqueting facilities in the city. It was set up with a               view to providing an elegant and superior banqueting space to cater to the varied requirements of their               clients. Whatever the celebration may be, big or small, it is their endeavor to make each celebration, a               grand success. They are perfect when it comes to hosting wedding ceremonies as they offer heavenly views               combined with lavish hospitality. The venue has indoor and outdoor spaces which can accommodate up to 500               people. They have a flexible catering policy. They also provide ample parking space for the guests. Their               warm welcoming nature and hospitality make your wedding experience very special. The location adds another               level of desire to this venue as it is situated on the outskirts, away from the noise and bustle of the               city.', 100000, 'Kanha Banquet Hall IMA Bhawan, Karamtoli Chowk', 'goa', 'Candolim', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(115, 'venues', 'Dos Equis Exotic Lounge, Bardez', 'Famous for its beaches and sunsets, Goa never fails to be a               top ranking city to host your special occasions. No doubt there are a multitude of venues available in Goa               for events of all budgets. Dos Equis Exotic Lounge is one such exotic property. This lounge is a large               spread of green lawn which has gained a reputation for itself for fantastic food and facilities. Their               excellent services and value attract the clients to book this venue for their big day and important               events. This sought after venue is sure to make your event memorable and give you memories to last a               lifetime..', 110000, 'Arrao Road, Olaulim-Pomburpa, Bardez, Goa', 'goa', 'Bardez', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(116, 'venues', 'Laxmi Vilas Palace Banquets', 'The three centuries old palace provides a gorgeous backdrop for a jaw-dropping wedding venue. Located in the midst of a lush green lawn, LVP Banquets is truly nothing short of magical. If you want a romantic and picturesque wedding, this is your venue for the day! While their decorators set up the place, their caterers can whip up the most amazing wedding feast for you and your guests..', 500, 'Ajwa Road, Baroda', 'gujarat', 'Baroda', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(117, 'venues', 'Aam Bagan', 'Located amidst vast stretches of mango orchards, Aam Bagan in Bokadev is an ideal wedding venue for you if you want a picturesque wedding. If you are planning a destination wedding in Gujarat, you must check out Aam Bagan for its lavish amenities and beautiful grounds. You can also get your own caterer and decorator to customize the event as per your needs...', 500, 'Sindhu Bhavan Road, Ahmedabad', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(118, 'venues', 'Thaker Farm', 'With vast stretches of lush green lawns, Thaker Farm makes an idyllic wedding venue for a destination wedding in Gujarat. Their in-house decorators can set up canopies, tents and other party areas for you and your guests. You can get your own caterer to treat your guests to a sumptuous feast while their decorators light up the place with gorgeous decorative lights...', 500, 'Gandhinagar, Ahmedabad', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(120, 'venues', 'Maple Farm', 'If you have always wanted a grand destination wedding in Gujarat, Maple Farm Party Plot might just be the one for you. With an elegant and spacious hall and a vast stretch of lawn, Maple Farm is truly an exquisite venue for a wedding. They also have an experienced team of decorators who can set up the place for your special day!...', 500, 'Chharodi, Ahmedabad', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(121, 'venues', 'Crown Plaza', 'Located in the Prashad Nagar area of Ahmedabad, Crowne Plaza in Ahmedabad City Centre is one of the most luxurious Gujarat destinations for a wedding. The place is so huge that you can easily host all the events of a wedding here, be it the Mehndi, Sangeet, Cocktail or reception party. The centre can host up to 2000 people, making it a viable option for people who have lots of guests to invite. Their in-house team caters to all your needs with the utmost care. The experienced chefs can prepare local and international cuisines with incredible precision...', 500, 'Ahmedabad City Center Road', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(122, 'venues', 'Narayani Heights', '...Narayani Heights is one of the best Gujarat destinations to host a Gujarati wedding. All the dÃ©cor at the venue is completely customisable, making it possible for you to personalise the wedding aesthetic as per your wishes.               There are 109 rooms available with tariffs ranging from â‚¹ 5,000 to â‚¹ 20,000. This variety of options in the price range just tells you how nicely the resort caters to the needs of people from different walks of life. Additionally, they offer multiple cuisines from around the world. They also customise the cooking process according to the Jain traditions. All these facilities make it a part of the list of ideal Gujarat destinations for a wedding.', 500, 'Dummy', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(123, 'venues', 'The House of MG', 'The House of Mangaldas Girdhardas is a heritage hotel that is one of the top Gujarat destinations for weddings with fewer guests. This venue is ideal for an intimate wedding, as they allow their venue to be booked for a party that has as little as 50 guests. This makes it perfect for someone looking for a destination wedding with just a handful of close relatives and friends.               The hotel specialises in creating dÃ©cor exactly the way you want, making it just perfect for people. The per-plate cost is around â‚¹ 900. The hotel has multiple event spaces like a sprawling terrace, banquet hall and the lawn area..', 500, 'Lal Darwaja, Ahmedabad', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(124, 'venues', 'The Gateway Hotel Athwalines', 'The Gateway Hotel Athwalines is a luxurious 5-star hotel in Surat. It is perfect for an upscale wedding with famous dignitaries as guests. This 5-star hotel has everything planned down to the T. You do not have to worry about anything at all as the hotels in-house team will look after everything. It can host anywhere between 750-1500 people in one go.               They offer multiple cuisines from India, like Mughlai, North Indian, South Indian, Street food and international cuisines like Italian, Continental and Chinese as well. Their per-plate cost is around â‚¹ 1,500.', 500, 'Ambika Niketan Road, Surat', 'gujarat', 'Surat', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(125, 'venues', 'Green YMCA Banquets & Lawn', 'Green YMCA Banquets And Lawn, Ahmedabad is taken care of by Green Leaves Management. It is an ideal venue for hosting your grand wedding, reception ceremony, and celebrations or events of any type. Green YMCA Banquets And Lawn, Makarba, Ahmedabad is a very well known place in the locality. So you can imagine how grand your event is going to be. The staff at this venue are professionals and skilled in their respective job, they make sure your function is executed well. YMCA Banquet Hall Ahmedabad serves palatable vegetarian delicacies to their guests. The stunning dÃ©cor of the venue gives a special touch to your big day..', 500, 'Makarba, Ahmedabad', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(126, 'venues', 'Jade Luxury Banquets', 'Jade Banquets is Indias premier destination to host exquisite events that symbolize grandeur & style. It operates multiple beautifully appointed banquet venues across India, offering world class hospitality and award winning catering to add elegance to your most treasured occasions. Jade Banquets has perfected the Art of Hospitality and enjoys a reputation of providing its guests with unique and memorable experiences that are highly regarded by the patrons. With world-class amenities and a responsive team that customizes and designs every part of the service, Jade is one of the most eminent venues in India. It is managed by professionals trained in the highest standards of international hospitality..', 500, 'Bodakdev, Ahmedabad', 'gujarat', 'Ahmedabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(127, 'venues', 'Unique Resorts Banquet Hall', 'Unique Resorts Banquet Hall is a banquet hall and marriage garden based out in the drool-worthy city of Jammu. This wedding venue has a kind of ambience that will steal your gaze and fixate on its interior decor and infrastructure. Their ambience style is contemporary with a touch of minimalism and refinement. They are a team of dedicated, passionate and hardworking staff who strive to fulfil their customers needs and would ensure that your wedding is the most unforgettable experience with memories you can cherish...', 91000, 'Jammu City, Jummu', 'jammu kashmir', 'Jammu City', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(128, 'venues', 'Windmill Resorts', 'Windmill Resorts Jammu is a wedding venue based out of Jammu. Indian weddings are one of the most glorious and exciting days for every couple in which everything from decor to food has to be planned carefully. One such detail is the venue where each of your ceremonies will be taking place you will be making tonnes of memories. So if you are searching for a fantastic venue to have all your pre and post-wedding functions hosted in teh most perfect manner then your search ends here with Windmill Resorts Jammu. They have a wonderful banquet hall which is apt for any of your nuptial ceremonies....', 91000, 'Jammu Junction, Jammu', 'jammu kashmir', 'Jammu City', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(129, 'venues', 'Kolu Group Of Houseboats', 'Kolu Group Of Houseboats is a wedding venue based out of Srinagar. It was in the year 1962, the very first Deluxe Luxury Houseboat was built in Dal lake which was named as Pride Of Kashmir which earned a lot of fame and is still pride to the owners. Kolu Group Of Houseboats is an embodiment of the family bond and as a result, the management through the years are been taken over by the following ages. At present we are proud of announcing the largest number of deluxe luxury houseboats in Kashmir. The entire control is taken care of by the management of Kolu brother which is led by Nazir Ahmed Kolu and brothers.....', 95000, 'Srinagar (North), Srinagar', 'jammu kashmir', 'Srinagar', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(130, 'venues', 'The Wedding University', 'The Wedding University is a stunning wedding resort located in Srinagar. To plan a perfect wedding, you need to choose the right venue as it is the critical element of organising a wedding flawlessly and in the best possible manner, and it should be the one which suits all your needs do hosting each of your weddings ceremonies the way you want. The Wedding University is the choice you should make if you are looking for a one-stop destination for all your requirements for a suitable wedding venue at a reasonable price range. It is well-equipped, and its staff ensures that your wedding is eventful and memorable for you and your guests...', 100000, 'Srinagar (North), Srinagar', 'jammu kashmir', 'Srinagar', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(131, 'venues', 'KC Emporia, Jammu', 'KC Emporia is a luxury banquet & resort based out of Jammu. The property is a modern piece of art that has a world-class hall room. The food catering is the best In town and the decor services will mesmerise you with its beauty and charm. The property has Grand lawns named Emporia Greens for hosting all your special functions. A wedding venue is one of the most famous places to host all kind of matrimonial events and if you want an ideal setting where you can take all your nuptials vows peacefully with your soulmates then you can opt for this venue you can book them for all your wedding commemorations so that you can have the most spectacular time with all your near and dear ones. They also make sure that all your celebrations are observed with great entertainment....', 98000, 'Srinagar (North), Srinagar', 'jammu kashmir', 'Jammu City, Jammu', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(132, 'venues', 'Blue Moon Banquets', 'Blue Moon Banquets is located in the city of Jammu. Weddings can be the most beautiful and special occasions in a persons life where they embark on a new journey with the ones they love. During all the wedding preparations, one of the most important decisions to make is the wedding venue, which speaks volumes about the kind of event that you want to have. If you are looking for a venue where you can host your wedding and all its other related functions without any hassle, then your search can end here. Blue Moon Banquets will ensure to provide you with quality services and hospitality to make your big day much more special....', 120000, 'Srinagar (North), Srinagar', 'jammu kashmir', 'Jammu City, Jammu', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(133, 'venues', 'G R Resort', '...G R Resort is a hotel and a wedding venue based out in the city of Jammu. It is one of the preferential venue partners to host corporate events as well as intimate gatherings and wedding functions. If you are finding the right venue where you can host your pre-wedding, wedding and post-wedding functions, then your search can end here. It is an ideal hotel wedding destination. They will ensure that your wedding is a gala event which is worth remembering a lifetime with an amazing bunch of highly-personalized services..', 130000, 'Jammu City, Jammu', 'jammu kashmir', 'Jammu City, Jammu', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(134, 'venues', 'Fortune Resort Heaven', 'Fortune Resort Heevan in Srinagar offers you with a venue in the valleys of Kashmir with a graceful vibe and appeal that makes your stay and your event especially a destination wedding very much dreamlike. The management staff attends to all your needs and demands so as to offer you with best services making your event truly memorable. The natural beauty of Srinagar just adds to the charm of the event..', 91000, 'Srinagar (North), Srinagar ', 'jammu kashmir', 'Jammu City, Jammu', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(135, 'venues', 'Kingsville - Banquet & Resort', 'Kingsville - Banquet & Resort is a wedding venue based in the city of Jammu. It offers you a fully air-conditioned indoor space where you can host all of your wedding celebrations and be assured that your function is the most fanatic one and you can host all sorts of functions with your family members as well. They have been into this hospitality industry from quite a long time and has a solid reputation for the kind of work that they offer. Kingsville - Banquet & Resort is a place that can be ideal for hosting large and grand functions in a great manner..', 95000, 'Jammu City, Jammu', 'jammu kashmir', 'Jammu City, Jammu', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(136, 'venues', 'Mascot Houseboats', 'Mascot Houseboats is a wedding venue based in Srinagar. Indian weddings are pleasant occasions which are celebrated with grandeur and elegance in which each detail is picked up carefully. One such essential detail is the venue where each of your ceremonies will be taking place. So if you are on a lookout for a wedding venue that offers you the best services and impressive hospitality for all your wedding celebrations then your search ends here with Mascot Houseboats. Its an ideal venue to host all your wedding functions with all your near and dear ones.?..', 140000, 'Srinagar (North), Srinagar', 'jammu kashmir', 'Jammu City, Jammu', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(137, 'venues', 'Calista Resort ', '             Calista Resort is located in Kapashera, South Delhi, and it is one of the most luxurious wedding venues in               the city. Its classy and elegant architecture combined with professional personnel will help you feel like               royalty on your big day. It has well-maintained and luxurious accommodation and has a professional               hospitality team to care for your every need. At Calista Resort, you can celebrate your big event, enhance               your well-being, and enter your new journey relaxed and rejuvenated...', 140000, 'Kapashera  - Samalkha - Rajokri, East Delhi', 'delhi', 'Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(138, 'venues', 'Veda Farms', '..    Veda Farms is a famous wedding venue based in Bijwasan, Delhi. The platform is well-equipped with all the               latest facilities and services to give you the excellent wedding experience of your lives. Planning a               perfect wedding involves choosing the right venue as per the suitability of your occasion and its               approachability and budget. Therefore if you are looking for a place that offers you royal hospitality and               excellent services, then Veda Farms is one of the ideal options. Located in the city, it is a 10 acres               perfect destination with exquisite decor, suitable for hosting lavish weddings that last for a lifetime.', 145000, ' 54, Bijwasan Rd, Kapas Hera Extension, New Delhi', 'delhi', 'Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(139, 'venues', 'Amrai Farms', 'Amrai Farms is a venue located in Kapashera, Delhi and is the one to choose for weddings, When               we talk about the wedding arrangement and planning, the first thing that pops in our minds is the venue as               it is the key element of any wedding functions. It sets the entire background for the ceremonies and even               the background for the photos and videos. If you are looking for a good venue to host any of your nuptial               ceremonies, then Amrai Farms is the choice that you should definitely make. Their staff will ensure to               make the wedding memorable for you and your guests..', 200000, ' Kapashera - Samalkha - Rajokri, South Delhi', 'delhi', ' South Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(140, 'venues', 'Solitaire Garden and Banquet', 'Solitaire Garden and Banquet is a venue, where you can host and organise any and every special celebration               in your life and be assured that they would be one of a kind and the most beautiful occasions in your               life. Choosing the right kind of venue is one of the most significant decisions that a couple takes as               they plan the wedding of their dreams and hope to live all of their desires and aspirations associated               with it and hope it will be the most cherished and wonderful celebration of their lives. To make your               function seems more exciting and active, they provide truckloads for facilities like essential lighting,               electricity & backup, valet parking and a bridal room...', 230000, 'Aruna Vartun Road ,North-West Delhi', 'delhi', ' North-West Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(141, 'venues', 'Araliayas Resort', '..Resort offers you with a great venue space to host and organize your special occasions like               wedding ceremonies and related functions, providing a serene atmosphere, a peaceful ambience and a quiet               demeanour of the lush green landscape. It is believed to be one of the most culturally rich and romantic               place where anyone would desire of a destination wedding.', 180000, 'Ram-Krishna , South-East Delhi', 'delhi', ' South-Eest Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(142, 'venues', 'Ramada Resort', 'Central is the most wanted destination for having a blissful and romantic wedding experience and Ramada               Resort & Spa offers you with the most scenic and beautiful suites and resorts location to organize your               marriage functions. The management and staff of Ramada Resort & Spa make sure that you and your guests               have a great hospitality experience..', 220000, '  Central Delhi', 'delhi', '  Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(143, 'venues', 'Yadu Greens', 'Yadu Greens is a stunning farmhouse on the GT Karnal Road of Delhi. This magnificent property offers its               discerning visitors a unique opportunity to celebrate their most special occasions with Ã©lan and ease.               This wedding venue offers multiple Stunning wedding venues with Exquisite DÃ©cor & Ambience combined with               Impeccable Hospitality and Lavish Catering. The banquets: Pratishtha, Yuvraj and Night Club-themed BLING,               are amongst Delhi NCRs most upmarket and grand wedding venues. It is the only venue with Exclusive entry               from NH-1 (Left side from Delhi to Karnal)...', 320000, 'GT Karnal Road - Alipur, North Delhi', 'delhi', '  Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(144, 'venues', 'Mohan Vilaas', '            Mohan Vilaas, situated in the busiest wedding destination of G.T. Karnal Road, serves as an ideal venue to               host any of your special events starting from the pre-wedding ceremonies to your grand wedding function.               The venue is easily accessible from all parts of Delhi NCR and has exquisite interiors to attract the               attention of all your guests. Mohan Vilaas is your destination for a wedding event that will be both               starry and filled with positive vibes for you to cherish it for the rest of your lives with your partner.               Offering the pinnacle of luxury and comfort, Mohan Vilaas is a popular choice for hosting grand functions....', 320000, 'Aarnal Road - Alipur, South Delhi', 'delhi', '  Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(145, 'venues', 'Elden Ring Motel And Resorts', '       Golden Ring Motel And Resorts is a magnificent venue for hosting a grand event located in the heart of               North Delhi. It has several spaces for indoor and outdoor ceremonies and features an amiable staff to               assist you with everything related to arranging a successful wedding. Whether a pre-wedding event or grand               reception party, there is no other place more suitable than Golden Ring Motel And Resorts. Be it any               pre-wedding ceremony, wedding ceremony, or post-wedding ceremony, you can hold these ceremonies               comfortably here and be assured that your wedding will be a memorable one....', 170000, 'GT Karnal Road - Alipur, North Delhi', 'delhi', '  Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active');
INSERT INTO `master_list` (`item_id`, `item_category`, `item_name`, `item_description`, `price`, `location`, `state`, `city`, `food_category`, `food_type`, `images`, `status`) VALUES
(146, 'venues', 'Hilltop Greens', '        Hilltop Greens is a wedding lawn farmhouse located in Faridabad. Its a blissful experience to find your               soul-mate finally, and to celebrate this auspicious union, we at Hilltop Greens provide the perfect choice               of spacious venues along with complete planning of even the minutest of details. The widespread venues               ranging from the luxurious Banquet Hall to versatile outdoor party lawns cater to minor parties and grand               weddings. They are designed in the most contemporary style combined with traditional aesthetics and               elegance to lend the perfect ambience for your dream celebration.....', 180000, 'Suraj Kund, Faridabad, Faridabad', 'delhi', '  Delhi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(147, 'venues', 'Trident, Cochin', '              When you have a desire for hosting your wedding at a summery and serene destination then, Trident Cochin               is one such venue that provides you with the apt ambience, feel and atmosphere. The management and staff               of Trident Cochin provide you with complete hospitality and banqueting facilities in order to offer you               with a great wedding venture or any other event that you and your guests will enjoy.....', 320000, 'Willingdon Island, Koch', 'kerala', 'Kochi', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(148, 'venues', 'Mayfair Banquets', ' With an ambition that promises to change market trends, hospitality standards and the concept of luxury               fusing with comfort and class, we present to you Mayfair Banquets Kerala, the largest luxury pillar less               banquet hall in Kerala.               We also have our own wedding planners, and event managers that have a long term experience in working with               a number of successful thematic weddings and events. This is what sets us apart as a one of the most               innovative banquet halls in Kolkata for marriage...', 350000, 'Dr. Basant Bapat rd, Kasaragod', 'kerala', 'Kasaragod', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(149, 'venues', 'Ramada Resort, Kochi', 'Ramada Resort, Kochi is one the most sought-after venues in the city of Kumbalam and is well-known for               hosting extravagant and elegant events and parties. This venue is easily accessible for all your guests to               reach at your venue without any problems. Choosing the right venue is the first step to organize a               flawless wedding and it should be chosen while keeping in mind all the requirements for your functions               that you want to host here. Ramada Resort, Kochi offers you a range of services with a stunning ambience               to plan a wonderful celebration. They will ensure to make your wedding an event which is worth remembering               a lifetime...', 250000, 'Ernakulam City, Kochi', 'kerala', 'Ernakulam', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(150, 'venues', 'Southern Panorama Indriya Resort & Spa', ' Southern Panorama Indriya Resorts & Spa is a wedding venue which is located in Munnar. It is one of the               fastest-growing hospitality brands in India. The venue has numerous banquet halls with a modern yet classy               interior. The overall vibe of the hotel has a touch of style and is a perfect place to host all your               wedding functions. They are the one who values the comfort of their guests also offering you with great               cuisine. Southern Panorama Indriya Resorts & Spa has that distinctly warm Indian hospitality that makes               you feel at home and the team put efforts to create value for money....', 180000, 'Munnar, Idukki', 'kerala', 'Idukki', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(151, 'venues', 'Emarald Ayurvedic Resort, Perinthalmanna', '     Emarald Ayurvedic Resort, Perinthalmanna is a banquet hall located in Malappuram and within close               proximity to Calicut Airport, it gives everyone a chance to be at your wedding without losing their way.               Within the name lies the experience that you can expect when you a relaxing and rejuvenating ambience.               Emarald Ayurvedic Resort, Perinthalmanna have services that are exceptional and they work hard to see all               their guests carry fond memories from the event. Pleasant and opulent against a scenic background will               nourish all your senses, and the wedding functions can be performed with delight and zeal..', 135000, 'Malappuram City, Malappuram', 'kerala', 'Idukki', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(152, 'venues', 'Lalit Resort, Kochi', ' Lalit Resort, Kochi is one the most sought-after venues in the city of Kumbalam and is well-known for               hosting extravagant and elegant events and parties. Lalit Resort, Kochi offers you a range of services               with a stunning ambience to plan a wonderful celebration. They will ensure to make your wedding an event               which is worth remembering a lifetime..', 125000, 'Ernakulam City, Ernakulam', 'kerala', 'Idukki', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(153, 'venues', 'Vasco Dagama Beach Resort, Kozhikode', 'Gama Beach Resort is a venue located in the city of Kozhikode and it is a gorgeous place to host               your festivities elegantly. The wedding venue is a non-negotiable part of the wedding planning and also               one of the major aspects of wedding planning because it is that one place that hosts your wedding               ceremonies and furthermore your relatives and companions who originate from everywhere throughout the               world to bless you and grace your fresh starts. Alongside being a wonderful retreat by the shoreline that               is tastefully engaging the faculties, Vasco Da Gama Beach Resort is fit for making astonishing courses of               action for your wedding...', 98000, 'Kozhikode City, Kozhikode', 'kerala', 'Kozhiokode', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(154, 'venues', 'The Lalit Resort & Spa Bekal', 'Located in Kerala, near the Arabian Sea, surrounded by river Nombilli, The Lalit Resort & Spa Bekal is a               gem of a venue in Gods own Country. With landscaped gardens, private lagoon, and touched by pristine               sandy beaches, The Lalit Resort & Spa Bekal can be rightfully described as a heavenly escape of luxury and               tranquillity. It is a perfect location for a magnificent wedding, blessed by serene ambience and               traditional, mesmerising settings...', 150000, ' Kasaragod City, Kasaragod', 'kerala', 'Kasaragod', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(155, 'venues', 'The Raviz Kadavu', ' The Raviz Kadavu is a luxury is a wedding setting based in Kozhikode that is wonderful to have your               wedding a lot of related festivities to make your weddings a never-ending one. Be it pre-wedding, wedding               or post-wedding assistance, they can make every one of your jobs effective one. They are amazing with               regards to facilitating huge Indian bridal functions as they offer magnificent chairs with warm               friendship. So in the event that you are searching for a spot that offers you an excellent scope of               guidance and help then you can choose them. They additionally offer a lot of other services to make your               function a deep one...', 180000, 'Kozikode City, Kozhikode', 'kerala', 'Kozhiokode', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(156, 'venues', 'Summit Hampton Hotel', '              Summit Hampton Hotel is a wedding venue situated in Idukki City. It is a one-stop destination for all your               needs for a suitable wedding venue. If you are looking for a great platform at a reasonable price range,               then this hotel is the choice that you should make. Choosing the right venue as per the suitability of               your occasion is a challenging task to do. Summit Hampton Hotel offers a beautiful lawn area to hold all               of your wedding rituals and ceremonies. Arrange the most beautiful event for you and your guests in this               space. Get ready for a dreamy wedding amongst the beautiful scenarios of Idukki...', 200000, 'Idukki City, Idukki', 'kerala', 'Idukki', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(157, 'venues', 'Taj Falaknuma Palace', 'Taj Falaknuma Palace is one of the most opulent heritage hotels in India, where you can host wedding and pre-wedding ceremonies. This heritage hotel is also a popular spot for hosting destination weddings in India. At Taj Falaknuma Palace you can choose to hold ceremonies for your wedding at the indoor or outdoor venues depending on your preference. The hotel also provides you with options ranging from splendid lawns, magnificent Rajasthani Gardens, a lavish Durbar Hall to the iconic Coronation Hall to host the wedding celebrations. Each of these venues at Taj Falaknuma Palace has a different seating capacity, ranging from a minimum of 60 guests to a maximum of 15000 guests..', 500, 'Engine Bowli, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(158, 'venues', 'Chowmahalla Palace', 'On your special day if you want to feel like a Prince or a Princess, then the grand wedding venue at Chowmahalla Palace is a perfect choice for you. Experience royalty at its best on the lush green lawn of Chowmahalla Palace, which is adorned with large fountains and the banquet hall that spells royalty of the by-gone era.               The decor and menu of the wedding ceremonies at Chowmahalla Palace can be customised by hiring wedding decorators and catering services of your choice.Price per plate:               Vegetarian: Approximately â‚¹900 onwards               Non-vegetarian: Approximately â‚¹1100 onwards..', 500, 'Motigalli, Khilwat, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(159, 'venues', 'Fort Grand', 'If you are looking for a quaint and serene space for your wedding venue, then Fort Grand in Hyderabad is a perfect wedding venue. This picturesque location blends royal architecture and modern amenities for both indoor as well as outdoor venues. Whether it is a grand celebration or an intimate celebration, Fort Grand has something to offer to everyone according to their preference. Their extensive menu has plenty of options for both vegetarian and non-vegetarian meals.               Price per plate:               Vegetarian: Approximately â‚¹900 onwards               Non-vegetarian: Approximately â‚¹1200 onwards..', 500, 'Shamshabad, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(160, 'venues', 'Taj Krishna', 'Taj Krishna is one of the most elegant luxury hotels in Hyderabad that has ample venue options for hosting wedding celebrations. The six indoor event venues at Taj Krishna provides you with a sophisticated space for organising pre-wedding ceremonies and wedding receptions. To make the hassle-free experience of hosting pre-wedding, wedding and post-wedding ceremonies at Taj Krishna, the in-house decorating and catering staff ensures that they fulfil all minute requirements for your big day.The plush surroundings, classy interiors and elegant rooms and suites at Taj Krishna make it a popular choice for wedding venues.Price per plate:               Veg:Approximately â‚¹2500 onwards               Non-veg:Approximately â‚¹3000 onwards..', 500, 'Banjara Hills, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(161, 'venues', 'Courtyard by Marriot', 'To make your wedding memorable, the staff at Courtyard by Marriot delivers exceptional service and hospitality. The experienced wedding planners staff leave no stone unturned in assisting and customising your wedding celebrations according to your preferences. Courtyard offers you to choose any venue from the 19 lavish wedding venues that include both indoor as well as outdoor venues. Whether you are planning to host a grand wedding for about 1000 guests or an intimate wedding for less than a 100 guests, you can opt for an indoor or outdoor venue at Courtyard that will suit your requirements as per your gathering. Price per plate:               Veg:Approximately â‚¹1400 onwards               Non-veg:Approximately â‚¹1500 onwards', 500, 'Kavadiguda, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(162, 'venues', 'The Golkonda Resorts', 'The Golkonda Resorts is a great venue for those who are looking to host a wedding amidst the scenic surrounds of this resort. It is equipped with 44 luxury villas and 24 premium rooms to accommodate your guests along with providing them with spaces such as a poolside bar, a poolside kitchen, all-day dining restaurants and spa services to pamper themselves.               The extensive lawns and elegant banquet halls at The Golkonda make it a perfect venue for an intimate wedding experience. Price per plate:               Veg: Approximately â‚¹1800 onwards               Non-veg: Approximately â‚¹2000 onwards', 500, 'Gandipet, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(163, 'venues', 'Aalankrita Resort', 'his tastefully designed resort blends lush green surroundings and modern amenities. The extensive area of the resort boasts of rooms, suites, penthouse rooms, cottage rooms and pool villa rooms to accommodate the guests.               There are several venues to conduct the ceremonies and parties related to weddings at Aalankrita Resort And Convention. The spacious lawns and banquet halls provide you with catering services and other in-house services for a memorable wedding celebration. The event spaces can accommodate from a minimum of 100 guests and a maximum of 800 guests at one time. Price per plate:               Veg: Approximately â‚¹800 onwards               Non-veg: Approximately â‚¹800 onwards', 500, 'Shamirpet, Secunderabad', 'telangana', 'Secunderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(164, 'venues', 'Sri Venkateswara Garden', 'The spacious lawn at Sri Venkateswara Garden is one of the grandest venues in Hyderabad to host a wedding on a lawn under the sky and the stars. The lush greenery and splendid ambience of this wedding venue makes it a popular choice for many in Hyderabad and Secunderabad.               The splendid 90,000 square feet lawn along with ample parking space, a function hall, dining halls and air-conditioned rooms will ensure that you enjoy indoor and outdoor facilities for various wedding ceremonies. You can also deck up the lawn area of Sri Venkateswara Garden for your dream wedding with innovative decor and lighting that are available at the premises.Price per plate:               Veg: Approximately â‚¹300 onwards', 500, 'Komapally, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(165, 'venues', 'Imperial Gardens', 'The four wedding venues at Imperial Gardens look like a wedding venue right out of the storybooks. The elegant architecture, tastefully designed spaces, exotic plants and ample space of each of the wedding venues at Imperial Gardens is sure to make a picture-perfect venue for wedding celebrations.               The outdoor event venues at Imperial Gardens are perfect for pre-wedding and wedding ceremonies. You can easily turn each of the spaces into your dream wedding venue with the help of the event planners. The courteous staff at Imperial Gardens are renowned for their impeccable service               . Price per plate:               Veg: Approximately â‚¹350 onwards               Non-veg: Approximately â‚¹450 onwards', 500, ' Sikh Road, Secunderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(166, 'venues', 'Summer Green Resort Palm Groves', 'Summer Green Resort blends the lush greenery of the surroundings along with splendid blue waters of the swimming pools and a soothing ambience. This elegant resort has facilities to host pre-wedding and wedding ceremonies along with accommodation facilities for the guests. The luxurious Kerala Cottage Room and Honeymoon Room are perfect for newlyweds.               For your dream wedding at this resort, you can opt for a lawn or a wedding hall as your wedding venue depending on the number of guests. The wedding venues can accommodate a minimum of 100 guests and a maximum of 1500 guests.               Price per plate:               Veg: Approximately â‚¹650 onwards               Non-veg: Approximately â‚¹750 onwards', 500, 'Shamirpet Mandal, Hyderabad', 'telangana', 'Hyderabad', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(167, 'venues', 'Stallone Manor', 'This is one of the largest banquet halls in the city with a 200 ft x 130 ft AC hall that matches the grandeur and grace of the Roman. They also have a spacious 200 ft x 130 ft lawn outside with the beautifully lit cascading fountain that will add more charisma to the decor. The types of cuisines on the offer are Mughlai, Avadhi, Punjabi Frontier, Marwari, Kashmiri, Hyderabadi, Chinese, Thai, Mexican, Lebanese, Italian, Mediterranean, and more.', 500, 'Pakhowal Road, Ludhiana', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(168, 'venues', 'Grand Wedding Villa ', 'As the name suggests, Grand Wedding Villa in Ludhiana is one of the prime choices for hosting a wedding in Punjab. This famous hotel is designed to host functions like wedding, ring ceremony and reception with large gatherings. The fully air-conditioned banquet hall can easily accommodate hundreds of guests. The villa has furnished rooms, kitchens along with a reception hall, and a marvelous lobby. The hotel has trained chefs that serve finger-licking cuisine to their guests..', 500, 'Pakhowal Road, Ludhiana', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(169, 'venues', 'Bath Castle', 'Bath Castle is one of the top wedding venues in Punjab. You will feel like you have reached your dream destination with the entrance that highlights beautiful fountains and a grand castle structure. It is spread over 7 acres of luxurious land with an impressive exterior as well as grandiose interior and a hall spread over 22,000 sq ft. that feels like you have entered a Mughal Fort with a modern touch. They provide you in-house catering, experienced & well-groomed staff & huge parking space...', 500, 'Pakhowal Road, Ludhiana', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(170, 'venues', 'Hyatt Regency', 'Located at the heart of the tri-city of Chandigarh, it is easily accessible from the other two key areas, Mohali and Panchkula, and 16 kilometers away from the Chandigarh International Airport and 4 kilometers from the Chandigarh Railway Station. The 5-star hotel wows you with its spacious and luxurious spaces, the fascinating interiors of which is inspired by French architect Le Corbusier with a brise-soleil faÃ§adeour hotel with rooms of area 36 to 200 square meters. They offer you Creative menus, imaginative settings, beautifully designed wedding locations, and professional wedding services....', 500, 'Business Park Phase 1', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(171, 'venues', 'JW Marriote', 'Their splendor Ballroom having a space of 8,407 sq ft. glows with radiance and is a perfect venue for your fairy tale wedding. With lush green lawns, that can accommodate up to 1,000 guests and situated in the citys business district, the hotel greets you with refined luxury and a modern sense of style. Their wedding planners will make sure that you get the best day of your life with the delicious wedding menu and wedding hosts....', 500, 'Dakshin Marg, Chandigarh', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(172, 'venues', 'Vivanta by Taj', 'Vivanta by Taj is one of the top wedding venues in Punjab.They offer you a couple of marvelous and lush spaces for your wedding to choose from. The ballroom I with an area of 1664.00 sq. ft. has also an additional pre-function space, ballroom II has the area of 2808.00 sq. ft. with grand green lawns attached to its side. The Capitol venue has a space of 552.75 sq. ft. and The Ballroom Annexe is ideal for your small intimate ceremonies. The best part is that they have an extravagant terrace lawn so you can get married under the blanket of stars....', 500, 'Block No. 9 Sector 17', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(173, 'venues', 'Hyatt', '...What could be better than having your wedding venue next to the Golden Temple? The hotel is just 30 minutes from the Guru Ram Das International Airport and holds the largest rooms inventory with 248 elegant guestrooms including 10 suites and a Presidential Suite. Their indoor banqueting with over 11647 sq ft space has the most elegant interiors and the mesmerizing outdoor venue Tented gardens can hold a grand wedding. They have a team of world-class wedding specialists to make your wedding just like how you want.', 500, 'G. T. Road, Amritsar', 'punjab', 'Amritsar', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(174, 'venues', 'Marrievilla Resorts', 'MarrieVilla Resorts, Ferozepur, Ludhiana is a gorgeous venue to celebrate the victory of your love with your better half. This venue is located on Ferozepur Road near the Pandori Play Ground which makes it convenient for all to reach there by either private and public transportation modes. MarrieVilla Resorts Ludhiana know that when it comes to weddings, you expect nothing but perfection. Therefore, It has a sprawling lawn and multiple banquet halls of contrasting sizes to take care of all your requirements. The lawn at Grand MarrieVilla Resorts is simply spectacular and can hold a huge crowd of guests, so you dont need to worry about shortening the guest list.', 500, 'Gill road, Ludhiana', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(175, 'venues', 'B.R. Resorts', 'BR Resorts, Amritsar is a farmhouse located on the Chheharta Bypass of the city. When you plan a lifetime event, like your wedding, you need to be considerate of a lot of things and choosing the venue is one of the main things to organise the perfect wedding. If you are looking for one such venue which can fulfil all your needs for the functions, then BR Resorts, Amritsar is the one-stop destination for you. Offering a plethora of services and amenities, this venue makes for an exemplary choice for any of your nuptial ceremonies..', 500, 'Gill road, Ludhiana', 'punjab', 'Ludhiana', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(176, 'venues', 'The Ummed', 'The Ummed Jodhpur, a Marwar palace with Rajasthani architectural elements, is tucked amidst acres of gardens. Its low-rise structures surround the expansive and impressive courtyard. From the palatial driveway to the luxurious rooms, everything makes guests feel like royalty. Wedding planner Ashish Bohra, of Perfexion Events, shares,This property is a kaleidoscope of gracious facets an exclusive porch, pathways for baraat processions, long private driveways, open spaces, and indoor venues. These make it perfect for hosting special occasions with luxury and grace, both on a grand or intimate scale', 500, 'Prem Nagar, Jodhpur', 'rajasthan', 'Jodhpur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(177, 'venues', 'Indana Hotels', 'The regal heritage and history of Jodhpur and Jaipur comes alive in Indana Hotels architecture and interiors. Set against the stunning backdrops of heritage, Indana Palace Jodhpur is a magnificent structure that showcases nuances of the Royal Marwar heritage with exquisite columns, intricate jaali work, regal arches, domes, and wide-open courtyards. Indana Palace Jaipur, on the other hand, welcomes you into the world of Maharajas and Maharanis of yore with its grand stone entry porch and exquisite hand-crafted doorway', 500, 'Shikargarh, Jodhpur', 'rajasthan', 'Jodhpur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(178, 'venues', 'Taj Aravali Resort', 'Spread across gently rolling slopes, the Taj Aravali Resort & Spa, Udaipur, is a sprawling property in the foothills of the lush Aravali mountain range. Flanked by green landscaped spaces, this property showcases traditional Rajasthani art and design in enchanting ways. Luxurious villas comprising single-pole desert tents offer interesting local decor elements such as the gokhra, (a low seating area by the window), and furnishings inspired by Mewars world-class equestrian heritage.', 500, 'Forest Chowki, Bujra', 'rajasthan', 'Bujra', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(179, 'venues', 'Welcom hotel Khimsar Fort and Dunes', 'Nestled on the edge of the Thar Desert lies a 16th-century fort with imposing walls and a majestic entrance. The Welcomhotel Khimsar Fort and Dunes is spread across 11 acres, and offers the option of luxe tents alongside well-furnished rooms. Wedding planner Niyati Khazanchi, of Desert Pearl Entertainment, shares, With a year-round outdoor swimming pool, terrace, free parking, and on-site restaurant, this property provides both comfort and convenience to guests and visitors. Every room offers stunning views of the desert', 500, 'Khimsar, Rajasthan', 'rajasthan', 'Khimsar', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(180, 'venues', 'Rambagh Palace', 'After years of being the Maharaja of Jaipurs home, Rambagh Palace was the first palace to be converted into a heritage hotel in India. It is extravagantly decorated with hand-carved marble jalis, sandstone balustrades, chattris and elaborate Mughal Gardens. Anant Khandelwal and Kartika Sharma of Indian Wedding Planners share, This regal architectural marvel truly epitomizes royal hospitality. Managed by the Taj Group, Rambagh Palace offers regality and modernity at the same time, and is a highly sought after property for couples looking for a royal wedding experience', 500, 'Bhawani Singh Rd, Jaipur', 'rajasthan', 'Khimsar', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(181, 'venues', 'Udai Kothi', 'A stunning rooftop pool surrounded by white arched marble pillars is just one of the highlights of the heritage boutique hotel Udai Kothi Udaipur. It lies a short distance from Lake Pichola, and offers guests 21st-century comforts coupled with an old-world charm. Awarded The Best Wedding Venue In Rajasthan, by New York Times magazine, and the Best Boutique Hotel In India, by National Geographic Traveller, this property guarantees memorable experiences at any event held here.', 500, 'Pichola, Udaipur', 'rajasthan', 'Udaipur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(182, 'venues', 'Shahpura House', 'If you want to get married amidst the hustle and bustle of Jaipur city, there isnt a better venue than Shahpura House. Located just 4 km away from the famous landmark Hawa Mahal, the hotel is actually a palace inherited from the royals of Shahpura and preserved intact with world-class facilities. The insides are decorated with grand domes and frescoes and the outside offers the majestic view of the Aravalli hills. So, making a perfect backdrop for your indoor or outdoor wedding setup..', 500, 'Bani Park , Jaipur', 'rajasthan', 'Udaipur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(183, 'venues', 'Shakun Hotels & Resorts', 'A newly developed property in Jaipurs posh colony C-Scheme, the hotel is all about offering a luxurious, comfortable and memorable experience to their guests. I have personally been to this hotel for wedding and roka events and can vouch for the superb event halls inside their premises that speak volumes of the grandeur they provide...', 500, 'Ashok Nagar, Jaipur', 'rajasthan', 'Jaipur', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(184, 'venues', 'Taj Bengal', 'Taj Bengal has more than six wedding venues in Kolkata, namely Portico, Oriental, Terrace Garden, Mandarin, Crystal Hall, and banquet lawns. The capacity ranges between 25 to 700 guests, and each of the venue areas have their own distinct features and decore.', 500, 'Alipore , Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(185, 'venues', 'ITC Sonar', 'The ITC Sonar features in this list of best wedding venues in Kolkata no just for the decor and services, but because of its enviable location. Away from hustle and bustle of the city, it hosts the most lavish wedding of Kolkata. The Pala (indoor venue area) steals the show away with its soft lighting and candles. The outdoor venue, called Sundarban Lawns is a lovely landscape garden suitable for an open air affair.', 500, 'Tangra , Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(186, 'venues', 'The Oberoi Grand Hotel', 'The Oberoi Grand Hotel has hosted luxe parties for erstwhile kings and British Bureaucrats in the olden days. Even today its grandeur as an elite wedding venue hasnt faded! It is among the best wedding venues in Kolkata having citys largest ballroom spanning over 19,000 sqft of area. It is also one of the best hotels in Kolkata.', 500, 'Taltala , Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(187, 'venues', 'Vedic Village', 'The Vedic Village is always listed among the most extravagant wedding places in Kolkata. It is also one of the most luxurious villas in Kolkata. The authorities take pride in being known as masters of exclusive themes such as big fat organic weddings, outdoor adventure weddings, exotic traditional weddings, and chic country weddings; and their wedding venues serve to these very well.               One of the best wedding resorts in Kolkata, the Vedic Village alongside four venue areas provides accommodation thats backed up with dining, spa, sports and other world-class facilities..', 500, 'Newtown, Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(188, 'venues', 'Club Verde Vista', 'umped up to make D-day the most memorable day of your life, Club Verde Vista features among the top open air wedding venues in Kolkata. There are both indoor and outdoor venues, with in-house decorators and caterers. With the venue, you can also consider a stay for guests as you get rooms (4 rooms available) for an average cost of INR 4,000 per room (above the venue charges).', 500, 'Upohar, Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(189, 'venues', 'Mangalam Banquets', 'One of the excellent yet somewhat cheap banquet halls in Kolkata for weddings, Mangalam Banquets is among the mid-sized wedding halls in South Kolkata that can host up to 300 guests. Theres an open road parking available with complimentary valet. If it is a comparatively small affair, this is the best choice for your special day.', 500, 'Gobra, Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(190, 'venues', 'Royal Bengal Room', 'Whatever the theme be for your wedding, all you need to do is to tell the decorators and you can have it. Not kidding, these people are the best in business and the Royal Bengal Room is beautiful and very spacious and somewhere where you should plan your dream wedding at. If your tastes are subtle then this is the place for you.', 500, 'Bidhannagar, Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(191, 'venues', 'Smriti Banquets', 'If you wish to serve alcohol to guests because you are a good host then Smriti Banquets is your best bet and offers the best solution to all your wedding related queries and doubts. Be it decor, food or anything else this wedding venue in Kolkata does everything right and is tucked away from the bustling city, offering quaint settings for your big day.', 500, 'Newtown, Kolkata', 'west bengal', 'Kolkata', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(192, 'transport', '14 Seater', '', 12000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(193, 'transport', 'Audi', '', 10000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(194, 'transport', 'Bmw', '', 13000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(195, 'transport', 'Bus', '', 15000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(196, 'transport', 'Ciaz', '', 9000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(197, 'transport', 'Ford', '', 9000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(198, 'transport', 'Kia SUV', '', 10000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(199, 'transport', 'Limousine', '', 15000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(200, 'transport', 'Tata City', '', 15000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active'),
(201, 'transport', 'Toyota Coaster', '', 18000, '', '', '', '', '', 'img1.jpg,img2.jpg,img3.jpg', 'active');

-- --------------------------------------------------------

--
-- Table structure for table `ongoing_orders`
--

DROP TABLE IF EXISTS `ongoing_orders`;
CREATE TABLE IF NOT EXISTS `ongoing_orders` (
  `user_id` int(10) NOT NULL,
  `item_id` int(10) NOT NULL,
  `category` varchar(500) NOT NULL,
  `name` varchar(500) NOT NULL,
  `price` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `state`
--

DROP TABLE IF EXISTS `state`;
CREATE TABLE IF NOT EXISTS `state` (
  `state_id` int(11) NOT NULL AUTO_INCREMENT,
  `state_name` varchar(20) NOT NULL,
  PRIMARY KEY (`state_id`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `state`
--

INSERT INTO `state` (`state_id`, `state_name`) VALUES
(1, 'maharashtra'),
(2, 'goa'),
(3, 'jammuandkashmir'),
(4, 'delhi'),
(5, 'kerala'),
(6, 'westbengal'),
(7, 'punjab'),
(8, 'gujarat'),
(9, 'telangana'),
(10, 'rajasthan');

-- --------------------------------------------------------

--
-- Table structure for table `transactions`
--

DROP TABLE IF EXISTS `transactions`;
CREATE TABLE IF NOT EXISTS `transactions` (
  `receipt_id` bigint(20) NOT NULL,
  `venue_name` varchar(255) NOT NULL,
  `venue_price` int(10) NOT NULL,
  `light_name` varchar(255) NOT NULL,
  `light_price` int(10) NOT NULL,
  `photo_name` varchar(255) NOT NULL,
  `photo_price` int(10) NOT NULL,
  `food_id` varchar(255) NOT NULL,
  `food_total` int(10) NOT NULL,
  `mehendi_name` varchar(255) NOT NULL,
  `mehendi_price` int(10) NOT NULL,
  `inv_card_name` varchar(255) NOT NULL,
  `inv_card_price` int(10) NOT NULL,
  `tran_name` varchar(255) NOT NULL,
  `tran_price` int(10) NOT NULL,
  `id_user` int(10) NOT NULL,
  `pending` int(2) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=75 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(14, 'Eeshan Vaidya', 'eeshan.vaidya.professional@gmail.com', '8fc2ec7f679adacbea6398eb0550cf33'),
(13, 'Sakshi Chikorde', 'sakshichikorde16@gmail.com', '45aac7a3110c4b2cd98796bdacddf662'),
(11, 'Huzaifa Faizee', 'huzaifataherfaiz@gmail.com', '42102e50e0add62ec8d9aa459a4006dd'),
(12, 'Aditi Palkar', 'aditipalkar111@gmail.com', '214a4c70683d0aae3e4986d24e161a0f'),
(15, 'Atharva Karkar', 'atharvakarkar@gmail.com', '21d3a1dca28f770145988b339478620e'),
(16, 'Komal Shrimal', 'komalshrimal02@gmail.com', '974bd820a99809d664cfd455ea3d7ad5'),
(17, 'Atharva Joshi', 'atharvaj1302@gmail.com', '29e952e06576e04edf8c5f185c27023b'),
(18, 'Just A Boy', 'justaboy@gmail.com', 'bf14c12f94557bf7dcf2a089e38015c8'),
(50, 'Komal Balan', 'dsinha@yahoo.co.in', '31e819859f87b7b7411c0a19736dac18'),
(48, 'Radha Shetty', 'mutti.nutan@yahoo.com', 'c5b425c9d0ba727c1bbfb0bb00f63272'),
(47, 'Ujwal Mani', 'parminder39@nadig.org', '41a29e53e7f20ea416ef12ad2815ded2'),
(46, 'Anannya Parikh', 'feroz.verma@yahoo.com', 'be818db43d2f5db01a3a04649e12e70b'),
(38, 'Charlie Hayer', 'ubail@rediffmail.com', 'a23369bd115ecf51855b9b3bea43800e'),
(63, 'Robert Davis', 'robertdavis@gmail.com', '684c851af59965b680086b7b4896ff98'),
(71, 'Eeshan', 'eeshan.vaidya.professional@gmail.com', 'e2975ecce841ca98e5368e9471619cda'),
(72, 'eeshan.vaidya.professional@gmail.com', 'eeshan.vaidya.professional@gmail.com', '51aca628cbc7bb656eebc7aace9d98a1'),
(73, 'eeshan.vaidya.professional@gmail.com', 'eeshan.vaidya.professional@gmail.com', 'e2975ecce841ca98e5368e9471619cda'),
(74, 'eeshanvaidya14@gmail.com', 'eeshanvaidya14@gmail.com', '741051f1929216889aefe84d2a15cffa');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
